context:
  name: pixitainer
  version: 0.3.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: .

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin
    - cp pixi-containerize $PREFIX/bin/pixi-containerize
    - chmod +x $PREFIX/bin/pixi-containerize

requirements:
  run:
    - apptainer >=1.4.5
    - bash

about:
  summary: Pixi is cool, apptainer is cool, let's make them both work together !
  license: BSD-3-Clause
  homepage: https://github.com/raphaelribes/pixitainer