context:
  name: pixitainer
  version: 0.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: .

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/bin
    - cp pixi-containerize $PREFIX/bin/pixi-containerize
    - chmod +x $PREFIX/bin/pixi-containerize

requirements:
  run:
    - __linux
    - apptainer >=1.4.5
    - bash

about:
  summary: Pixi is cool, apptainer is cool, let's make them both work together !
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/raphaelribes/pixitainer
  repository: https://github.com/raphaelribes/pixitainer
  description: It takes too much time to build and rebuild your Apptainer/Singularity containers but pixi is hard to integrate in your pipelines ? Pixitainer is here to help you containerize your pixi pipelines into Apptainer/Singularity containers easily.
